.reset_session
;
; Create all the input files needed for the steep scarp investigation
;
.run make_steep_scarp_parameter_files.idl



.reset_session
;
; Run models to produce flat input files
;
 restore,'steepscarp_flat_parameters_200s.sav'
 print,thermal_model_v07(preprocess_thermal_model(sp))
 restore,'steepscarp_flat_parameters_600s.sav'
 print,thermal_model_v07(preprocess_thermal_model(sp))



.reset_session
;
; Run models for different dust thicknesses
;
.run
tt = [10.0,8.0,6.0,4.0,2.0,0.0]
for i=0,n_elements(tt)-1L do begin
 restore,'steepscarp_'+string(fix(tt(i)),format='(I03)')+'mm_parameters.sav'
 print,thermal_model_v07(preprocess_thermal_model(sp))
endfor
end



.reset_session
;
; Run models for different slopes & aspects
;
.run
for j=30.d0,80.d0,5.d0 do begin
for i=90.d0,270.d0,15.0d0 do begin
 restore,'steepscarp_'+string(j,format='(I02)')+'_'+string(i,format='(I03)')+'_parameters.sav'
 print,thermal_model_v07(preprocess_thermal_model(sp))
endfor
endfor
end



.reset_session
;
; Run stress model for the zero lag case
;
restore,stress_from_temp_results('steepscarp_000mm_results.sav',d=1d-3)



;
; ZERO LAG SUMMARY
;
.reset_session
restore,'steepscarp_flat_parameters_200s.sav'
print,thermal_model_v07(preprocess_thermal_model(sp))
 
.reset_session
restore,'steepscarp_000mm_parameters.sav'
print,thermal_model_v07(preprocess_thermal_model(sp))

.reset_session
.com ../stress/stress_from_temp_results.pro
restore,stress_from_temp_results('steepscarp_000mm_results.sav',d=1d-3)




.reset_session
;
; Plot CO2 frost thicknesses for different dust thicknesses
;

tt = [10.0,8.0,6.0,4.0,2.0,0.0]

restore,'steepscarp_'+string(fix(tt(0)),format='(I03)')+'mm_results.sav'
ls(where(ls LT 30)) = ls(where(ls LT 30)) + 360.0
v = where(ls EQ min(ls))
pp = plot(shift(ls,-v),shift(mc,-v),dimensions=[800,600],xstyle=1,xrange=[0,360],xtitle='L$_s$',ytitle='CO$_2$ Frost (kg m$^{-2}$)',xthick=2,ythick=2,name=string(fix(tt(0)),format='(I2)')+'mm')
pp.ytickfont_size=20
pp.xtickfont_size=20
pp.ylog=1

restore,'steepscarp_'+string(fix(tt(4)),format='(I03)')+'mm_results.sav'
ls(where(ls LT 30)) = ls(where(ls LT 30)) + 360.0
pp2 = plot(shift(ls,-v),shift(mc,-v),name=string(fix(tt(4)),format='(I2)')+'mm',linestyle=2,/overplot)

restore,'steepscarp_'+string(fix(tt(5)),format='(I03)')+'mm_results.sav'
ls(where(ls LT 30)) = ls(where(ls LT 30)) + 360.0
pp3 = plot(shift(ls,-v),shift(mc,-v),name=string(fix(tt(5)),format='(I2)')+'mm',linestyle=3,/overplot)

pp.xrange=[340,380]
pp.yrange=[0.01,1000]
pp.ytickunits='exponent'
pp.thick=2
pp2.thick=2
pp3.thick=2
pp.xtickvalues = [340,350,360,370,380]
pp.xtickname   = strcompress([340,350,360,10,20],/re)

ll = legend(target=[pp,pp2,pp3],position=[375,1],/data)
ll.font_size=18
pp.save,'~/Desktop/byrne_et_al_avalanche_scarp/lag_thickness.jpg',border=10,resolution=150



.reset_session
;
; Figure for example temperature structure with zero lag on 70-SW slope
;
restore,'steepscarp_000mm_results.sav'
ict=0L                                       ; Layer at which the ice table begins

v  = where(ls EQ min(ls)) 
tt = reverse(shift(sav_allt(*,ict:*),-v,0),2)   ; only ice temperatures shifted so Ls=0 is the start of the array, reversed in the depth direction
zz = reverse(z(ict:*))
lls = shift(ls,-v)
itt = shift(itt,-v)

dd = dindgen((size(tt))[1]) + 0.5
z2 = dindgen((size(tt))[2])

tn = [(dindgen(9)+1.0)/10.0,(dindgen(9)+1.0)/100.0,dindgen(9)+1.0,10.0,20.0,30.d0]
tv = interpol(z2,zz,tn) 
tn = strarr(n_elements(tv))
tn(0) = '0.01'
tn(9) = '0.1'
tn(18) = '1.0'
tn(27) = '10.0'

ttn = indgen(13.0)*30.0
ttv = interpol(dd,lls,ttn)
ttn = strcompress(fix(ttn),/re)

iii = image(tt,dd,z2,rgb_table=33, axis_style=0, min_value=150, max_value=250,ythick=2,xthick=2,/interpolate,dimensions=[1600,600],margin=[0.1,0.1,0.1,0.1],aspect_ratio=0)
aax = axis(0,target=iii,location=[0,0],thick=2,title='Sol'  ,axis_range=range(dd),coord_transform=[0.0,sp.dt/88775.d0],tickfont_size=16)
aaxx = axis(0,target=iii,location=[0,n_elements(z2)],thick=2,title='L$_S$'  ,axis_range=range(dd),coord_transform=[0.0,1.0],tickvalues=ttv,tickname=ttn,major=0,minor=0,tickfont_size=16,textpos=1,tickdir=1)
aay = axis(1,target=iii,location=[0,0],thick=2,title='Depth (m)',axis_range=range(z2),coord_transform=[0.0,1.0],tickvalues=tv,tickname=reverse(string(tn)),major=0,minor=0,tickfont_size=16)
aay = axis(1,target=iii,location=[max(dd),0],thick=2,axis_range=range(z2),coord_transform=[0.0,1.0],tickvalues=tv,tickname=reverse(string(tn)),major=0,minor=0,tickfont_size=16,textpos=1,tickdir=1,showtext=0)
ccc = colorbar(target=iii,thick=2,position=[0.92,0.1,0.94,0.9],title='Temperature (K)',font_size=16,font_style=1,ORIENTATION=1, TEXTPOS=1, TAPER=1)
iii.save,'~/Desktop/example_temp.jpg',border=10,resolution=150

pp = plot(dd,itt,dimensions=[1600,400], name='Temperature',margin=[0.1,0.15,0.1,0.1])
pp.xthick=2
pp.ythick=2
pp.ytickfont_size=18
pp.xtickfont_size=18
pp.ytitle='Temperature (K)'
pp.xtitle='L$_{s}$'
pp.xrange=[0,360]
pp.yrange=[150,250]
pp.xtickvalues= ttv
pp.xtickname=ttn
pp.xminor=2
pp.save,'~/Desktop/example_temp_surf.jpg',border=10,resolution=150


